### ISSUE TITLE
JavaScript-error:

### ISSUE THREAD

**Issue by jjogal** [noxone/regex-generator#383] opened 2023-04-09 09:42 UTC
An error occurred with these details:
- Exception: `t is undefined`
- Commit ID: `6d1199bb9aa0ebe5de8f78c59f20d5c0b3e02a86`
- UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
- Vendor: 
- Language: en-US
- Platform: Linux x86_64
- CPU: Linux x86_64
- TouchPoints: 0
- Plugins:
  - PDF Viewer
  - Chrome PDF Viewer
  - Chromium PDF Viewer
  - Microsoft Edge PDF Viewer
  - WebKit built-in PDF
- StackTrace: TypeError: t is undefined
@https://regex-generator.olafneumann.org/regex-generator.js?commitId=6d1199bb9aa0ebe5de8f78c59f20d5c0b3e02a86:1:636932
cs@https://regex-generator.olafneumann.org/regex-generator.js?commitId=6d1199bb9aa0ebe5de8f78c59f20d5c0b3e02a86:1:557249
@https://regex-generator.olafneumann.org/regex-generator.js?commitId=6d1199bb9aa0ebe5de8f78c59f20d5c0b3e02a86:1:637835
@https://regex-generator.olafneumann.org/regex-generator.js?commitId=6d1199bb9aa0ebe5de8f78c59f20d5c0b3e02a86:1:638848
@https://regex-generator.olafneumann.org/regex-generator.js?commitId=6d1199bb9aa0ebe5de8f78c59f20d5c0b3e02a86:1:626111
@https://regex-generator.olafneumann.org/regex-generator.js?commitId=6d1199bb9aa0ebe5de8f78c59f20d5c0b3e02a86:1:648694
@https://regex-generator.olafneumann.org/regex-generator.js?commitId=6d1199bb9aa0ebe5de8f78c59f20d5c0b3e02a86:1:643674
@https://regex-generator.olafneumann.org/regex-generator.js?commitId=6d1199bb9aa0ebe5de8f78c59f20d5c0b3e02a86:1:643682
654/i/Au/<@https://regex-generator.olafneumann.org/regex-generator.js?commitId=6d1199bb9aa0ebe5de8f78c59f20d5c0b3e02a86:1:584392

**Comment by noxone** [comment] 2023-04-10 10:55
Hi, thank you for filing this. This issue seems to be the same as #380. So I will close this as duplicate and work on 380. Fix is being prepared...

Duplicate of #380

**Comment by noxone** [comment] 2023-04-10 10:55
Duplicate of #380

**Closed** 2023-04-10 10:55 UTC
